//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinKeyToo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinKeyToo.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Device Mappings.
        /// </summary>
        internal static string AllDeviceMappingsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllDeviceMappingsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Mapping.
        /// </summary>
        internal static string DeviceMappingViewModel_DisplayName {
            get {
                return ResourceManager.GetString("DeviceMappingViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is missing.
        /// </summary>
        internal static string DeviceMappingViewModel_Error_MissingAssemblyFileName {
            get {
                return ResourceManager.GetString("DeviceMappingViewModel_Error_MissingAssemblyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device selection is missing.
        /// </summary>
        internal static string DeviceMappingViewModel_Error_MissingDeviceInstanceGuid {
            get {
                return ResourceManager.GetString("DeviceMappingViewModel_Error_MissingDeviceInstanceGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence is missing.
        /// </summary>
        internal static string DeviceMappingViewModel_Error_MissingInputCombination {
            get {
                return ResourceManager.GetString("DeviceMappingViewModel_Error_MissingInputCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action is missing.
        /// </summary>
        internal static string DeviceMappingViewModel_Error_MissingTypeName {
            get {
                return ResourceManager.GetString("DeviceMappingViewModel_Error_MissingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save device mapping without all requirements met..
        /// </summary>
        internal static string DeviceMappingViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("DeviceMappingViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new mapping.
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewDeviceMapping {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewDeviceMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not run at startup.
        /// </summary>
        internal static string MainWindowViewModel_Command_DoNotRunAtStartup {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_DoNotRunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        internal static string MainWindowViewModel_Command_RunAtStartup {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all mappings.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllDeviceMappings {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllDeviceMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinKeyToo.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
